### ISSUE TITLE
Respect reduced motion settings

### ISSUE THREAD

**Issue by sarayourfriend** [mwmbl/front-end-original#18]
While the minimalist homepage is quite pleasant, the movement on it can be jarring for some folks. For these cases there is the [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query that can be used to develop alternative (usually much more minimal to no) animations.

Originally I had overcomplicated the potential solution (you can see it in the revisions of this issue). There is a simple fix though: wait until the user submits the query, just like other forms. At this point, move the search bar. With reduced motion enabled, pop the search bar up to the top without a transition. This will solve the movement and will also remove the possibility that the movement happens while you are typing, as in the video below.

https://user-images.githubusercontent.com/24264157/178134795-6124b694-efc6-4200-a439-eaf3c32050a5.mp4

Anyway, love the project! I will be following it closely. If you ever want to pop over to [Openverse](https://github.com/wordpress/openverse) we're also doing a non-profit search engine thing, though admittedly with a specific niche and goal in mind.

Also, if you're happy to accept a PR and any have suggestions for which solution you'd like to see implemented, I'd be glad to take a go at it :slightly_smiling_face:

**Comment by ColinEspinas** [comment]
Adding support for `prefers-reduced-motion` is definitely something we would want to implement. You are free to submit any PR to the project concerning this feature or any other idea. 

Thanks for this issue!
