### ISSUE TITLE
Intermediary queries in browser history

### ISSUE THREAD

**Issue by qualterz** [mwmbl/front-end-original#20]
While you typing a search query, with each character URL updates and this commits in browser history.
Suggest to update URL on search form lost focus or on page scroll.

<details>
<summary>This is how browser history looks like</summary>

![Browser History Flood](https://user-images.githubusercontent.com/38355785/178147296-f2feba62-5e5c-44b8-9f66-8af273d99817.png)

</details>

**Comment by ColinEspinas** [comment]
Thanks, I'll look into a more reasonable approach of handling the browser history.

**Comment by daoudclarke** [comment]
I believe this is not an issue in the new UI.
