### ISSUE TITLE
Load Results In Limit & A Button To Show The Next Results!

### ISSUE THREAD

**Issue by ghost** [mwmbl/front-end-original#31]
Hello.

This 'Mwmbl' search engine loads all results in once, and there is no button or any arrow to load the next. And isn't it will effect the performance of the website? It is very important to implement this feature. And a arrow to go back to previous result, there is no-need to create a new html page for the next results, just modify html elements.

Thanks.

**Comment by ColinEspinas** [comment]
Hey @OneByteTools, thanks for opening this issue, this is a good idea but could be impossible to do with the current API.

This repository is only about the official client/front-end.

@daoudclarke is there a pagination option from the search API?

**Comment by daoudclarke** [comment]
Sorry, just saw this - we discussed pagination but it's not a priority right now.
