### ISSUE TITLE
Use atomic design to organize components 

### ISSUE THREAD

**Issue by ColinEspinas** [mwmbl/front-end-original#9]
Currently there are not a lot of components, but as the project grows we'll need to tidy things a bit more for maintainability.

Organizing our components using [Atomic Design](https://bradfrost.com/blog/post/atomic-web-design/) could be a great first step in that direction.

My proposal is to create 3 directories in the current `components` directory, one for each component type (atoms, molecules, organisms).

We don't have pages currently as we rely on a main `index.html` to display our components, the `pages` directory should only be added once/if we implement routing and multiple pages.

**Comment by daoudclarke** [comment]
Sounds good
